general {
    hide_cursor = true
    # grace = 2
    # fade_in = 0.15
}


background {
    monitor =
    path = /home/visanth/Pictures/wallpapers/03.png
    blur_passes = 1
    blur_size = 4
    brightness = 0.7
    contrast = 0.9
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true

    outer_color = rgb(c8d4cc)
    inner_color = rgb(6f9079)
    font_color = rgb(ffffff)

    fade_on_empty = false
    placeholder_text = <i>Password...</i>

    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_family = "JetBrainsMono Nerd"
    # font_weight = 600
    font_size = 40
    color = rgb(ffffff)

    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:5000] echo "$(cat /sys/class/power_supply/BAT0/capacity)%"
    # NOTE: If your system supports native variables, you can use text = $BATTERY instead
    # text = $BATTERY
    font_family = "JetBrainsMono Nerd"
    # font_weight = 500
    font_size = 20
    color = rgb(ffffff)

    position = 0, 10        
    halign = center
    valign = center
}
