-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "thunar"
local menu = "rofi -show drun -theme ~/.config/rofi/config.rasi"


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()

    -- Waybar
    hl.exec_cmd("waybar")

    -- AWW wallpaper daemon
    hl.exec_cmd("awww-daemon >/dev/null 2>&1")


    -- Bluetooth tray
    hl.exec_cmd("blueman-applet")

    -- Lock Screen/Something
    hl.exec_cmd("hypridle")

end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 8,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 0.80,

        shadow = {
            enabled      = true,
            range        = 8,
            render_power = 3,
            color        = 0xaa0000,
        },

        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            vibrancy = 0.20,
            popups = true,
        },

    },


    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- Smart gaps:
-- 1 tiled window  -> larger margin around the window
-- 2+ tiled windows -> minimal gaps between windows

hl.workspace_rule({
    workspace = "w[tv1]",
    gaps_out = 8, -- minimal padding from screen edge
    gaps_in = 4,  -- small gap between windows
})

hl.workspace_rule({
    workspace = "f[1]",
    gaps_out = 8,
    gaps_in = 4,
})

-- Rounded corners, no borders
hl.window_rule({
    name = "rounded-no-border",
    match = {
        float = false,
    },
    border_size = 0,
    rounding = 10,
})


-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"


---------------------
---- APPLICATIONS ---
---------------------

-- Terminal
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))

-- File manager
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))

-- Application launcher
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))


---------------------
---- WINDOWS -------
---------------------

-- Close active window
hl.bind(mainMod .. " + Q", hl.dsp.window.close())

-- Toggle floating
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))

-- Fullscreen
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())

-- Toggle pseudo-tile
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())

-- Toggle split
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))


---------------------
---- FOCUS ---------
---------------------

-- Arrow keys
hl.bind(mainMod .. " + left",
    hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + right",
    hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + up",
    hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + down",
    hl.dsp.focus({ direction = "down" }))

-- NOTE:
-- J is reserved for togglesplit above.
-- Use ALT + J for moving focus down.
hl.bind(mainMod .. " + ALT + J",
    hl.dsp.focus({ direction = "down" }))


---------------------
---- MOVE WINDOWS ---
---------------------

hl.bind(
    mainMod .. " + SHIFT + left",
    hl.dsp.window.move({ direction = "left" })
)

hl.bind(
    mainMod .. " + SHIFT + right",
    hl.dsp.window.move({ direction = "right" })
)

hl.bind(
    mainMod .. " + SHIFT + up",
    hl.dsp.window.move({ direction = "up" })
)

hl.bind(
    mainMod .. " + SHIFT + down",
    hl.dsp.window.move({ direction = "down" })
)


---------------------
---- WORKSPACES -----
---------------------

-- Workspaces 1-9
for i = 1, 9 do

    hl.bind(
        mainMod .. " + " .. i,
        hl.dsp.focus({ workspace = i })
    )

    hl.bind(
        mainMod .. " + SHIFT + " .. i,
        hl.dsp.window.move({ workspace = i })
    )

end


-- Workspace 10 = 0
hl.bind(
    mainMod .. " + 0",
    hl.dsp.focus({ workspace = 10 })
)

hl.bind(
    mainMod .. " + SHIFT + 0",
    hl.dsp.window.move({ workspace = 10 })
)


---------------------
---- WORKSPACE SCROLL
---------------------

hl.bind(
    mainMod .. " + mouse_down",
    hl.dsp.focus({ workspace = "e+1" })
)

hl.bind(
    mainMod .. " + mouse_up",
    hl.dsp.focus({ workspace = "e-1" })
)


---------------------
---- MOUSE ----------
---------------------

-- Super + Left click = move window
hl.bind(
    mainMod .. " + mouse:272",
    hl.dsp.window.drag(),
    { mouse = true }
)

-- Super + Right click = resize window
hl.bind(
    mainMod .. " + mouse:273",
    hl.dsp.window.resize(),
    { mouse = true }
)


-----------------------------
---- VOLUME / AUDIO --------
-----------------------------

-- Volume up
hl.bind(
    "XF86AudioRaiseVolume",
    hl.dsp.exec_cmd(
        "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"
    ),
    {
        locked = true,
        repeating = true
    }
)

-- Volume down
hl.bind(
    "XF86AudioLowerVolume",
    hl.dsp.exec_cmd(
        "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
    ),
    {
        locked = true,
        repeating = true
    }
)

-- Speaker mute
hl.bind(
    "XF86AudioMute",
    hl.dsp.exec_cmd(
        "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
    ),
    {
        locked = true
    }
)

-- Microphone mute
hl.bind(
    "XF86AudioMicMute",
    hl.dsp.exec_cmd(
        "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
    ),
    {
        locked = true
    }
)


-----------------------------
---- BRIGHTNESS ------------
-----------------------------

-- Your actual display:
-- intel_backlight
--
-- Increase
hl.bind(
    "XF86MonBrightnessUp",
    hl.dsp.exec_cmd(
        "brightnessctl -d intel_backlight set +5%"
    ),
    {
        locked = true,
        repeating = true
    }
)

-- Decrease
hl.bind(
    "XF86MonBrightnessDown",
    hl.dsp.exec_cmd(
        "brightnessctl -d intel_backlight set 5%-"
    ),
    {
        locked = true,
        repeating = true
    }
)


-----------------------------
---- MEDIA -----------------
-----------------------------

hl.bind(
    "XF86AudioPlay",
    hl.dsp.exec_cmd("playerctl play-pause"),
    {
        locked = true
    }
)

hl.bind(
    "XF86AudioPause",
    hl.dsp.exec_cmd("playerctl play-pause"),
    {
        locked = true
    }
)

hl.bind(
    "XF86AudioNext",
    hl.dsp.exec_cmd("playerctl next"),
    {
        locked = true
    }
)

hl.bind(
    "XF86AudioPrev",
    hl.dsp.exec_cmd("playerctl previous"),
    {
        locked = true
    }
)


-----------------------------
---- SYSTEM ----------------
-----------------------------

-- Reload Hyprland
hl.bind(
    mainMod .. " + SHIFT + R",
    hl.dsp.exec_cmd("hyprctl reload")
)

-- Exit Hyprland
hl.bind(
    mainMod .. " + SHIFT + Q",
    hl.dsp.exit()
)


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Prevent applications from forcing maximize
hl.window_rule({
    name = "suppress-maximize-events",

    match = {
        class = ".*",
    },

    suppress_event = "maximize",
})


-----------------------------
---- BLUETOOTH --------------
-----------------------------

-- Open Blueman
hl.bind(
    mainMod .. " + B",
    hl.dsp.exec_cmd("blueman-manager")
)


-----------------------------
---- AUDIO CONTROL ----------
-----------------------------

-- Open PulseAudio/PipeWire volume control
hl.bind(
    mainMod .. " + A",
    hl.dsp.exec_cmd("pavucontrol")
)


-----------------------------
---- SCREENSHOT -------------
-----------------------------

-- Full screen
hl.bind(
    mainMod .. " + SHIFT + P",
    hl.dsp.exec_cmd(
        "grim ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png"
    )
)

-- Select region
hl.bind(
    mainMod .. " + SHIFT + S",
    hl.dsp.exec_cmd(
        "grim -g \"$(slurp)\" ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png"
    )
)


-----------------------------
---- XWAYLAND FIX -----------
-----------------------------

hl.window_rule({
    name = "fix-xwayland-drags",

    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },

    no_focus = true,
})


-----------------------------
---- BLUEMAN WINDOW ---------
-----------------------------

hl.window_rule({
    name = "blueman-floating",

    match = {
        class = "blueman-manager",
    },

    float = true,
    center = true,
})


-----------------------------
---- PAVUCONTROL WINDOW -----
-----------------------------

hl.window_rule({
    name = "pavucontrol-floating",

    match = {
        class = "pavucontrol",
    },

    float = true,
    center = true,
})


-----------------------------
---- HYPRLAND RUN -----------
-----------------------------

hl.window_rule({
    name = "move-hyprland-run",

    match = {
        class = "hyprland-run",
    },

    move = "20 monitor_h-120",
    float = true,
})

-----------------------------
---- ROFI GLASS -------------
-----------------------------
hl.layer_rule({
    name = "rofi-glass",

    match = {
        namespace = "^rofi$",
    },

    blur = false,
    blur_popups = false,
    dim_around = false,
})


-- Toggle wallpaper
hl.bind(
    mainMod .. " + W",
    hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpaper.sh >/dev/null 2>&1")
)

-----------------------------
---- MOBILE RIGHT LAYOUT ----
-----------------------------

local mobile_mode = false
local mobile_window = nil

-- Your monitor is 1920x1200 @ 1.5 scale.
-- Firefox measured:
--   381 Hyprland units -> ~500 CSS px
--
-- Therefore ~300 Hyprland units gives approximately
-- a 390px CSS viewport.
local MOBILE_WIDTH = 300


hl.layout.register("mobile-right", {

    recalculate = function(ctx)

        local targets = ctx.targets
        local area = ctx.area

        local mobile = nil
        local others = {}


        --------------------------------------------------
        -- Find the window selected for mobile mode
        --------------------------------------------------

        for _, target in ipairs(targets) do

            local win = target.window

            if win
                and mobile_window
                and tostring(win.address) == tostring(mobile_window)
            then

                mobile = target

            else

                table.insert(others, target)

            end

        end


        --------------------------------------------------
        -- Safety fallback
        --------------------------------------------------

        if not mobile then

            for i, target in ipairs(targets) do
                target:place(ctx:column(i, #targets))
            end

            return

        end


        --------------------------------------------------
        -- Mobile width
        --------------------------------------------------

        local mobile_width = math.min(MOBILE_WIDTH, area.w)

        local left_width = area.w - mobile_width


        --------------------------------------------------
        -- LEFT SIDE
        --
        -- All other windows occupy the remaining area.
        --------------------------------------------------

        if #others > 0 and left_width > 0 then

            local each_height = area.h / #others

            for i, target in ipairs(others) do

                target:place({
                    x = area.x,
                    y = area.y + ((i - 1) * each_height),
                    w = left_width,
                    h = each_height,
                })

            end

        end


        --------------------------------------------------
        -- RIGHT SIDE
        --
        -- Selected window gets the complete usable height.
        --------------------------------------------------

        mobile:place({

            x = area.x + left_width,
            y = area.y,

            w = mobile_width,
            h = area.h,

        })

    end,

})


-----------------------------
---- SUPER + M --------------
-----------------------------

hl.bind("SUPER + M", function()

    local win = hl.get_active_window()

    if not win then
        return
    end


    --------------------------------------------------
    -- ENTER MOBILE MODE
    --------------------------------------------------

    if not mobile_mode then

        mobile_window = tostring(win.address)

        mobile_mode = true


        -- Activate our custom layout on the current
        -- workspace.
        hl.workspace_rule({
            workspace = tostring(hl.get_active_workspace().id),
            layout = "lua:mobile-right",
        })


    --------------------------------------------------
    -- EXIT MOBILE MODE
    --------------------------------------------------

    else

        mobile_mode = false
        mobile_window = nil


        -- Return to Hyprland's normal layout using
        -- the workspace rule.
        --
        -- Change this to your normal layout if needed.
        hl.workspace_rule({
            workspace = tostring(hl.get_active_workspace().id),
            layout = "dwindle",
        })

    end

end)


-----------------------------
---- LOCK / POWER ----------
-----------------------------

local lock_cmd = [[ln -sf "$(awww query | sed -n 's/.*currently displaying: image: //p' | tr -d '[:space:]')" /home/visanth/.cache/current_wallpaper.png && sleep 0.1 && hyprlock]]

-- Super + L = Update wallpaper symlink + Lock
hl.bind(
    mainMod .. " + L",
    hl.dsp.exec_cmd(lock_cmd)
)

-- Super + Shift + L = Suspend
hl.bind(
    mainMod .. " + SHIFT + L",
    hl.dsp.exec_cmd("systemctl suspend")
)

-- Super + X = Power menu
hl.bind(
    mainMod .. " + X",
    hl.dsp.exec_cmd("~/.config/rofi/power-menu.sh")
)

-----------------------------
---- MOUSEPAD GLASS ---------
-----------------------------

hl.window_rule({
    name = "mousepad-glass",

    match = {
        class = "^mousepad$",
    },

    opacity = 0.85,
})
